package com.javaman.subterranean.models;

// Date: 2015-03-15 12:51:02 AM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX








import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraftforge.fml.relauncher.Side;
import net.minecraftforge.fml.relauncher.SideOnly;
@SideOnly(Side.CLIENT)
public class ModelFlumph extends ModelBase
{
  //fields
    ModelRenderer body;
    ModelRenderer eyeStem1;
    ModelRenderer Shape1;
    ModelRenderer Shape2;
    ModelRenderer eyeStem2;
    ModelRenderer leg2;
    ModelRenderer leg3;
    ModelRenderer leg1;
    
  public ModelFlumph()
  {
    textureWidth = 128;
    textureHeight = 32;
    
      body = new ModelRenderer(this, 0, 0);
      body.addBox(0F, 0F, 0F, 32, 1, 16);
      body.setRotationPoint(-16F, 0F, -9F);
      body.setTextureSize(128, 32);
      body.mirror = true;
      setRotation(body, 0F, 0F, 0F);
      eyeStem1 = new ModelRenderer(this, 0, 18);
      eyeStem1.addBox(-1F, -12F, -1F, 2, 12, 2);
      eyeStem1.setRotationPoint(12F, 0F, -1F);
      eyeStem1.setTextureSize(128, 32);
      eyeStem1.mirror = true;
      setRotation(eyeStem1, 0F, 0F, 0.2094395F);
      Shape1 = new ModelRenderer(this, 8, 20);
      Shape1.addBox(-3F, -18F, -3F, 6, 6, 6);
      Shape1.setRotationPoint(12F, 0F, -1F);
      Shape1.setTextureSize(128, 32);
      Shape1.mirror = true;
      setRotation(Shape1, 0F, 0F, 0.2094395F);
      Shape2 = new ModelRenderer(this, 8, 20);
      Shape2.addBox(-3F, -18F, -3F, 6, 6, 6);
      Shape2.setRotationPoint(-12F, 0F, -1F);
      Shape2.setTextureSize(128, 32);
      Shape2.mirror = true;
      setRotation(Shape2, 0F, 0F, -0.2094395F);
      eyeStem2 = new ModelRenderer(this, 0, 18);
      eyeStem2.addBox(-1F, -12F, -1F, 2, 12, 2);
      eyeStem2.setRotationPoint(-12F, 0F, -1F);
      eyeStem2.setTextureSize(128, 32);
      eyeStem2.mirror = true;
      setRotation(eyeStem2, 0F, 0F, -0.2094395F);
      leg2 = new ModelRenderer(this, 0, 0);
      leg2.addBox(-1F, 0F, -1F, 2, 12, 2);
      leg2.setRotationPoint(-10F, 1F, -3F);
      leg2.setTextureSize(128, 32);
      leg2.mirror = true;
      setRotation(leg2, 0F, 0F, 0F);
      leg3 = new ModelRenderer(this, 0, 0);
      leg3.addBox(-1F, 0F, -1F, 2, 12, 2);
      leg3.setRotationPoint(9F, 1F, -2F);
      leg3.setTextureSize(128, 32);
      leg3.mirror = true;
      setRotation(leg3, 0F, 0F, 0F);
      leg1 = new ModelRenderer(this, 0, 0);
      leg1.addBox(0F, 0F, 0F, 2, 12, 2);
      leg1.setRotationPoint(0F, 0F, 0F);
      leg1.setTextureSize(128, 32);
      leg1.mirror = true;
      setRotation(leg1, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    body.render(f5);
    eyeStem1.render(f5);
    Shape1.render(f5);
    Shape2.render(f5);
    eyeStem2.render(f5);
    leg2.render(f5);
    leg3.render(f5);
    leg1.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5,entity);
  }
}

