package com.javaman.subterranean.models;

//Date: 2015-03-06 11:21:44 PM
//Template version 1.1
//Java generated by Techne
//Keep in mind that you still need to fill in some blanks
//- ZeuX







import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraftforge.fml.relauncher.Side;
import net.minecraftforge.fml.relauncher.SideOnly;
@SideOnly(Side.CLIENT)
public class ModelFailSnail extends ModelBase
{
//fields
 ModelRenderer base;
 ModelRenderer shell;
 ModelRenderer eyestem1;
 ModelRenderer mase1;
 ModelRenderer mase2;
 ModelRenderer eyestem2;
 ModelRenderer eyestem3;
 ModelRenderer mase4;
 ModelRenderer eyestem4;
 ModelRenderer mase3;
 ModelRenderer shellR1;
 ModelRenderer shellR2;
 ModelRenderer shellR3;
 ModelRenderer shellL3;
 ModelRenderer shellL2;
 ModelRenderer shellL1;

public ModelFailSnail()
{
 textureWidth = 256;
 textureHeight = 128;
 
   base = new ModelRenderer(this, 0, 0);
   base.addBox(-6F, 0F, -12F, 24, 8, 48);
   base.setRotationPoint(0F, 16F, 0F);
   base.setTextureSize(256, 128);
   base.mirror = true;
   setRotation(base, 0F, 0F, 0F);
   shell = new ModelRenderer(this, 0, 57);
   shell.addBox(0F, 0F, 0F, 16, 32, 32);
   shell.setRotationPoint(-1F, -16F, 0F);
   shell.setTextureSize(256, 128);
   shell.mirror = true;
   setRotation(shell, 0F, 0F, 0F);
   eyestem1 = new ModelRenderer(this, 96, 0);
   eyestem1.addBox(-2F, -12F, -2F, 4, 12, 4);
   eyestem1.setRotationPoint(-3F, 16F, -9F);
   eyestem1.setTextureSize(256, 128);
   eyestem1.mirror = true;
   setRotation(eyestem1, 0F, 0F, 0F);
   mase1 = new ModelRenderer(this, 0, 0);
   mase1.addBox(-3F, -18F, -3F, 6, 6, 6);
   mase1.setRotationPoint(-3F, 16F, -9F);
   mase1.setTextureSize(256, 128);
   mase1.mirror = true;
   setRotation(mase1, 0F, 0F, 0F);
   mase2 = new ModelRenderer(this, 0, 0);
   mase2.addBox(-3F, -23F, -3F, 6, 6, 6);
   mase2.setRotationPoint(14F, 17F, -9F);
   mase2.setTextureSize(256, 128);
   mase2.mirror = true;
   setRotation(mase2, 0F, 0F, 0F);
   eyestem2 = new ModelRenderer(this, 96, 0);
   eyestem2.addBox(-2F, -17F, -2F, 4, 16, 4);
   eyestem2.setRotationPoint(14F, 17F, -9F);
   eyestem2.setTextureSize(256, 128);
   eyestem2.mirror = true;
   setRotation(eyestem2, 0F, 0F, 0F);
   eyestem3 = new ModelRenderer(this, 96, 0);
   eyestem3.addBox(0F, -20F, -2F, 4, 19, 4);
   eyestem3.setRotationPoint(-5F, 17F, -3F);
   eyestem3.setTextureSize(256, 128);
   eyestem3.mirror = true;
   setRotation(eyestem3, 0F, 0F, 0F);
   mase4 = new ModelRenderer(this, 0, 0);
   mase4.addBox(-3F, -23F, -3F, 6, 6, 6);
   mase4.setRotationPoint(5F, 17F, -7F);
   mase4.setTextureSize(256, 128);
   mase4.mirror = true;
   setRotation(mase4, 0F, 0F, 0F);
   eyestem4 = new ModelRenderer(this, 96, 0);
   eyestem4.addBox(-2F, -17F, -2F, 4, 16, 4);
   eyestem4.setRotationPoint(5F, 17F, -7F);
   eyestem4.setTextureSize(256, 128);
   eyestem4.mirror = true;
   setRotation(eyestem4, 0F, 0F, 0F);
   mase3 = new ModelRenderer(this, 0, 0);
   mase3.addBox(-1F, -26F, -3F, 6, 6, 6);
   mase3.setRotationPoint(-5F, 17F, -3F);
   mase3.setTextureSize(256, 128);
   mase3.mirror = true;
   setRotation(mase3, 0F, 0F, 0F);
   shellR1 = new ModelRenderer(this, 96, 57);
   shellR1.addBox(0F, 0F, 0F, 4, 24, 24);
   shellR1.setRotationPoint(-5F, -12F, 4F);
   shellR1.setTextureSize(256, 128);
   shellR1.mirror = true;
   setRotation(shellR1, 0F, 0F, 0F);
   shellR2 = new ModelRenderer(this, 0, 15);
   shellR2.addBox(0F, 0F, 0F, 4, 16, 16);
   shellR2.setRotationPoint(-9F, -8F, 8F);
   shellR2.setTextureSize(256, 128);
   shellR2.mirror = true;
   setRotation(shellR2, 0F, 0F, 0F);
   shellR3 = new ModelRenderer(this, 96, 105);
   shellR3.addBox(0F, 0F, 0F, 4, 8, 8);
   shellR3.setRotationPoint(-13F, -5F, 12F);
   shellR3.setTextureSize(256, 128);
   shellR3.mirror = true;
   setRotation(shellR3, 0F, 0F, 0F);
   shellL3 = new ModelRenderer(this, 96, 105);
   shellL3.addBox(0F, 0F, 0F, 4, 8, 8);
   shellL3.setRotationPoint(23F, -5F, 12F);
   shellL3.setTextureSize(256, 128);
   shellL3.mirror = true;
   setRotation(shellL3, 0F, 0F, 0F);
   shellL2 = new ModelRenderer(this, 0, 15);
   shellL2.addBox(0F, 0F, 0F, 4, 16, 16);
   shellL2.setRotationPoint(19F, -8F, 8F);
   shellL2.setTextureSize(256, 128);
   shellL2.mirror = true;
   setRotation(shellL2, 0F, 0F, 0F);
   shellL1 = new ModelRenderer(this, 96, 57);
   shellL1.addBox(0F, 0F, 0F, 4, 24, 24);
   shellL1.setRotationPoint(15F, -12F, 4F);
   shellL1.setTextureSize(256, 128);
   shellL1.mirror = true;
   setRotation(shellL1, 0F, 0F, 0F);
}

public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
{
 super.render(entity, f, f1, f2, f3, f4, f5);
 setRotationAngles(f, f1, f2, f3, f4, f5, entity);
 base.render(f5);
 shell.render(f5);
 eyestem1.render(f5);
 mase1.render(f5);
 mase2.render(f5);
 eyestem2.render(f5);
 eyestem3.render(f5);
 mase4.render(f5);
 eyestem4.render(f5);
 mase3.render(f5);
 shellR1.render(f5);
 shellR2.render(f5);
 shellR3.render(f5);
 shellL3.render(f5);
 shellL2.render(f5);
 shellL1.render(f5);
}

private void setRotation(ModelRenderer model, float x, float y, float z)
{
 model.rotateAngleX = x;
 model.rotateAngleY = y;
 model.rotateAngleZ = z;
}

public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5,Entity entity)
{
 super.setRotationAngles(f, f1, f2, f3, f4, f5,entity);
}

}
